package org.bob.android.app.contactmanager.persistence.beans;

import android.content.ContentValues;
import android.database.Cursor;
import android.util.Log;
import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import org.bob.android.app.contactmanager.utilities.DBConstants;
import org.bob.android.app.contactmanager.utilities.Logger;

import java.util.Date;

/**
 * Created by roberto.gatti on 04/09/2014.
 */
@DatabaseTable(tableName = DBConstants.ADDRESS_TABLE_NAME)
public class AddressBean extends BaseObject
{
    public static final String[] PROJECTION = new String[2] ;

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true, columnName = DBConstants.DEFAULT_ID_FIELD_NAME)
    private int id;

    @DatabaseField(index = true, columnName = DBConstants.ADDRESS_ADDRESS_FIELD_NAME, dataType = DataType.STRING)
    private String address;

    @DatabaseField
    private long tmst_upd;

    @DatabaseField
    private long tmst_ins;

    static
    {
        PROJECTION[0] = DBConstants.DEFAULT_ID_FIELD_NAME;
        PROJECTION[1] = DBConstants.ADDRESS_ADDRESS_FIELD_NAME;
    }

    /**
     * Costruttore di default (per ormlite)
     */
    public AddressBean() { }

    /**
     * Costruttore col solo id.
     * @param id
     */
    public AddressBean(int id)
    {
        this.setId(id);
    }

    /**
     * Costruttore full.
     * @param id
     * @param address
     */
    public AddressBean(int id, String address)
    {
        this.setId(id);
        this.setAddress(address);
    }


    /**
     * Costruttore porcata legato all'integrazione ORMLite - ContentProvider...
     * @param cv
     */
    public AddressBean(ContentValues cv)
    {
        this.setAddress((String) cv.get(DBConstants.ADDRESS_ADDRESS_FIELD_NAME));
        if ( cv.get(DBConstants.DEFAULT_ID_FIELD_NAME) != null )
            this.setId(Integer.parseInt(cv.get(DBConstants.DEFAULT_ID_FIELD_NAME).toString()));
    }

    /**
     * Costruttore per il recupero dell'oggetto da db.
     * @param cursor
     */
    public AddressBean(Cursor cursor)
    {
        if ( cursor != null )
        {
            this.setId(cursor.getInt(cursor.getColumnIndex(DBConstants.DEFAULT_ID_FIELD_NAME)));
            this.setAddress(cursor.getString(cursor.getColumnIndex(DBConstants.ADDRESS_ADDRESS_FIELD_NAME)));
        }
    }

    /* ********************************************************************* */
    /*                           SETTER AND GETTER                           */
    /* ********************************************************************* */

    @Override
    public void setId(int id) { this.id = id; super.set_Id(this.id); }
    public void setAddress(String address) { this.address = address; }

    @Override
    public int getId() { return this.id; }
    public String getAddress() { return this.address; }

    /* ********************************************************************* */
    /*                          OVERRIDDEN METHODS                           */
    /* ********************************************************************* */

    /*       Object class     */

    @Override
    public int hashCode()
    {
        int hashcode = 1;
        // hashcode += ( Math.abs(this.getId()) * 11 );
        hashcode += (this.getAddress().toUpperCase().hashCode() * 13);
        return hashcode;
    }

    @Override
    public boolean equals(Object o)
    {
        if ( o instanceof AddressBean )
        {
            AddressBean obj = (AddressBean) o;
            if ( obj == null )
            {
                Logger.v(this.getClass(), "AddressBean.equals: parametro a null!");
                return false;
            }
            // Se hanno l'id valorizzato controllo semplicemente l'hashcode
            if ( this.getId() > 0 && obj.getId() > 0)
            {
                Logger.v(this.getClass(), "|-- Id degli oggetti sono uguali? --> " + String.valueOf(this.getId() == obj.getId()));
                return this.getId() == obj.getId() ? true : false;
            }
            // ... altrimenti controllo l'hashcode
            Logger.v(this.getClass(), "|-- hashcode dei due oggetti: this: " + this.hashCode() + " -- param :" + obj.hashCode() );
            return this.hashCode() == obj.hashCode();
        }
        else
        {
            Logger.v(this.getClass(), "AddressBean.equals: parametro non di tipo AddressBean");
            return false;
        }
    }

    @Override
    protected Object clone() throws CloneNotSupportedException
    {
        return new AddressBean(this.getId(), this.getAddress());
    }

    @Override
    public String getDescription()
    {
        return this.getAddress();
    }

    @Override
    public ContentValues getContentValues()
    {
        ContentValues cv = new ContentValues();
        cv.put(DBConstants.OBJECT_CLASS_TYPE_KEY, this.getClass().getName());
        cv.put(DBConstants.ADDRESS_ADDRESS_FIELD_NAME, this.getAddress());
        return cv;
    }
}
